version: '3'
services:
  db:
    build:
      context: ./
      dockerfile: ./docker/db/Dockerfile
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=NULL
    volumes:
      - ./data:/data/db
      - ./db/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - 5432
    ports:
      - 5432:5432

  back:
    build:
      context: ./
      dockerfile: ./docker/back/Dockerfile
    restart: always
    environment:
      - NODE_ENV=dev
      - DB_HOST=db
    volumes:
      - .:/home/node/app
      - /usr/src/app/node_modules
    ports:
      - 8080:8080
    links:
      - db
    depends_on:
      - db
